name: scrollable_calendar
description: A scrollable and highly customizable widget for Flutter.
version: 0.0.1
developer: JD Freolo <jd.freolo@gmail.com>
homepage: https://github.com/jdfreolo/scrollable-calendar

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: